# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5dd5805decb29a38d1b3b51c0c98e7cd7e989acc0f60f322601c2658f34847bc68c47d918ac223ca3066c1b4df0bbc8a5f0ae3a04d8a5e170e4699344b6a84

test:
  secret_key_base: 01f81df37bc44ce40c56d2b43da933d15b80d6cf01081ec9c7062f4934b0822101cc61159439d1047e92566804a6a4b5727344620a057ad199f89c91a2c83ac7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
